name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Compilar la imagen localmente en el runner de GitHub
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/docker-flask:1.0.0 .

      # 2. Login en GitHub Container Registry usando el Token automático
      - name: Login en GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Publicar la imagen creada
      - name: Publicar la imagen creada
        run: docker push ghcr.io/${{ github.repository_owner }}/docker-flask:1.0.0

      # 4. Mostrar variables informativas
      - name: Mostrar variables (solo locales, no secretos)
        run: |
          echo "Preparando conexión SSH hacia la VPS..."
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "Usuario: ${{ secrets.VPS_USER }}"
          echo "Puerto: ${{ secrets.VPS_SSH_PORT }}"

      # 5. Ejecutar comandos dentro de tu servidor VPS por SSH
      - name: Ejecutar despliegue en la VPS vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "¡Conectado exitosamente por SSH a la VPS!"
            hostname
            whoami
            apt update 