name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: 2. Iniciar sesion en GitHub Packages (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Validar y Publicar la imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-flask:1.0.0

      - name: 4. Mostrar variables informativas (Corregido con VPS_USERS)
        run: |
          echo "Preparando conexión SSH hacia la VPS..."
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "Usuario: ${{ secrets.VPS_USERS }}"
          echo "Puerto: ${{ secrets.VPS_SSH_PORT }}"

      # Modificado a @master con timeouts añadidos para romper el bloqueo de red
      - name: 5. Pasar archivos desde git al VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERS }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          timeout: 40s
          command_timeout: 5m
          source: "docker-compose.yml,Makefile"
          target: "/home/${{ secrets.VPS_USERS }}/landinga"

      # Modificado a @master con timeouts añadidos para estabilizar la sesión SSH
      - name: 6. Ejecutar despliegue en el VPS usando Makefile
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERS }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          timeout: 40s
          command_timeout: 5m
          script: |
            cd /home/${{ secrets.VPS_USERS }}/landinga
            make deploy